spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tAUZdnxDAFVPAPoRCzm
      secret-key: 5DA0eSu4mCkluBnMN9h6ZskJIV0l29
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: gulimall-ky
  application:
    name: gulimall-third-party

server:
  port: 30000